name:                xic
version:             0.1.0.0
github:              "zachary0kent/xic"
license:             BSD3
author:              "Zachary Kent"
copyright:           "2022 Zachary Kent"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zachary0kent/xic#readme>

dependencies:
- base >= 4.7 && < 5
- array
- bytestring
- utf8-string
- formatting
- cleff
- cleff-plugin
- conduit
- filepath
- optparse-applicative

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fplugin=Cleff.Plugin
- -Wno-name-shadowing

library:
  source-dirs: src

executables:
  xic-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xic

tests:
  xic-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xic

default-extensions:
- ApplicativeDo
- BangPatterns
- BlockArguments
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable 
- DerivingStrategies 
- DerivingVia 
- EmptyCase
- ExistentialQuantification
- FlexibleContexts 
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving 
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- DuplicateRecordFields
- OverloadedStrings
- PatternSynonyms
- QuantifiedConstraints
- RankNTypes
- RoleAnnotations
- ScopedTypeVariables 
- StandaloneDeriving
- StandaloneKindSignatures
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- UnliftedNewtypes
- ViewPatterns
- ImportQualifiedPost

build-tools: 
- alex
